const ADD_EXPENSE = "ADD_EXPENSE";
const REMOVE_EXPENSE = "REMOVE_EXPENSE";
const UPDATE_EXPENSE = "UPDATE_EXPENSE";
const ADD_CATEGORY = "ADD_CATEGORY";
const REMOVE_CATEGORY = "REMOVE_CATEGORY";
const SET_CATEGORIES = "SET_CATEGORIES";

export {
  ADD_CATEGORY,
  REMOVE_CATEGORY,
  ADD_EXPENSE,
  REMOVE_EXPENSE,
  UPDATE_EXPENSE,
  SET_CATEGORIES,
};
